name: RuboCop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagickwand-dev
          bundle install
      - name: Run RuboCop
        run: bundle exec rubocop --format github
